# The URL the site will be built for
base_url = "royrustdev.com"

# The site title and description; used in feeds by default.
title = "Rust Software Engineer | royrustdev"
description = "I'm an autodidact Software Enginner & DevOps Enginner. I create Cloud-Native application with Rust. My hunger for knowledge & passion to impelement it are helping me to make this world a better place."

# The default language; used in feeds.
default_language = "en"

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

render_emoji = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
