# The URL the site will be built for
base_url = "royrustdev.com"

# The site title and description; used in feeds by default.
title = "Rust Software Engineer | royrustdev"
description = "I'm a Rust Software Enginner specializing in backend and dev-tools. I'm currently working on containerized microservices, managed by Docker and Kubernetes. I like to write efficient, secure, clean and documented software, by using test driven development (TDD) with a continuous integration environment"

# The default language; used in feeds.
default_language = "en"

# When set to "true", the generated HTML files are minified.
minify_html = true

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

render_emoji = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# Feed
generate_feed = true
feed_filename = "rss.xml"
taxonomies = [
    { name = "tags", feed = true },
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
author = "Nrishinghananda Roy"
github = "royrustdev"
twitter = "royrustdev"
email = "royrustdev@gmail.com"

[extra.logo]
path = "royrustdev.svg"
source = "https://royrustdev.com/royrustdev.svg"

[extra.cover]
path = "royrustdev.png"
source = "https://royrustdev.com/royrustdev.png"
